---
- name: Install MariaDB package key
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db

- name: Add MariaDB source 
  apt_repository: repo='deb http://mirror.jmu.edu/pub/mariadb/repo/5.5/ubuntu trusty main' state=present

- name: Install MariaDB package
  apt: name={{item}} state=present
  with_items:
    - mariadb-server
    - python-mysqldb

- name: Start MariaDB Service
  service: name=mysql state=started enabled=yes
